# fly.toml app configuration file generated for loonar on 2023-11-04T08:33:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "loonar"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
